name: tpm2-openssl-provider
version: "1.0"
summary: OpenSSL tpm2 provider
description: |
  Provides tpm2.so OpenSSL provider for use with the system openssl.
  Connect after install: snap connect tpm2-openssl-provider:tpm :tpm

confinement: strict
grade: stable
base: core24

apps:
  dummy:
    command: usr/bin/true
    plugs: [tpm]

parts:
  tpm2-provider:
    plugin: nil
    stage-packages:
      - tpm2-openssl
      - libtss2-esys-3.0.2-0
      - libtss2-tctildr0
      - libtss2-rc0
      - libtss2-mu-4.0.1-0
    prime:
      - usr/lib/x86_64-linux-gnu/ossl-modules/tpm2.so
      - usr/lib/x86_64-linux-gnu/libtss2-*.so*
    override-pull: |
      apt-cache search tpm2 | grep openssl
      craftctl default
